[output.log_levels]
NONE = ''
DEBUG = '\u001b[36:36m' # CYAN: \x1b[36:36m
INFO = '\u001b[38;20m'  # GREY: \x1b[38;20m
WARNING = '\u001b[33;20m' # YELLOW: \x1b[33;20m
ERROR = '\u001b[31;20m' # RED: \x1b[31;20m
CRITICAL = '\u001b[31;1m'  # BOLD RED: \x1b[31;1m

[output.file]
enable = false
level = "INFO"
path = "/tmp/"
format = "(%(asctime)s)[%(name)s][%(levelname)s]::%(message)s"
name = "template_%s.log"

[output.console]
enable = true
level = "INFO"
format = "[%(levelname)s]::%(message)s"
use_colors = true
